---
title: numerique.gouv.fr
timezone: Europe/Paris
collections:
  actualites:
    title: Actualités
    output: true
    Data:
      address_ref: 
  communiques:
    title: Communiqués
    output: true
  evenements:
    title: Evènements
    output: true
  missions-dinsic:
    title: Les missions de la Dinsic
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: actualites
  values:
    layout: post
    is_une: true
    categories:
    - Article
    chapeau-text: 
    une-ou-diaporama:
    - image: 
      legende: 
      alternative-textuelle: 
    auteur: 
    permalink: "/actualites/:title/"
- scope:
    path: ''
    type: communiques
  values:
    communique_file: uploads/exemple.pdf
    layout: communique
    permalink: "/espace-presse/:title/"
    categories:
    - Communiqué de presse
    chapeau-text: 
    une-ou-diaporama:
    - image: 
      legende: 
      alternative-textuelle: 
    contact-presse:
      name: Rachel Wadoux
      tel:
      - 01.71.21.11.98
      - 06.84.72.02.00
      email: rachel.wadoux@modernisation.gouv.fr
- scope:
    path: ''
    type: evenements
  values:
    layout: post
    permalink: "/evenements/:title/"
url: https://numerique.gouv.fr
categories:
- main
language: fr
markdown: kramdown
description: Le site officiel de la DINSIC
plugins:
- sass
- jekyll-sitemap
- jekyll-algolia
include:
- ".htaccess"
- _pages
exclude:
- ".DS_Store"
- ".circleci/"
- bower.json
- composer.json
- composer.lock
- DOC.md
- "/gulp/"
- gulpfile.js
- LICENSE.md
- Makefile
- node_modules
- npm-debug.log
- package.json
- README.md
- rev-manifest.json
- yarn.lock
- yarn-error.log
- "/ansible/"
- "/node_modules/"
incremental: true
compress_html:
  ignore:
    envs:
    - development
highlighter: rouge
algolia:
  application_id: OCGRURLBFM
  index_name: jekyll-dinsic
  nodes_to_index: p,li,blockquote
  extensions_to_index:
  - md
  - markdown
  files_to_exclude:
  - _pages/index.md
  - _pages/algolia.md
  - _pages/espace-presse.md
  - _pages/actualites.md
  - _pages/rechercher.md
  settings:
    searchableAttributes:
    - unordered(title)
    - ordered(headings)
    - unordered(chapeau-text)
    - unordered(content)
    - unordered(collection,categories,tags)
    highlightPreTag: "<mark>"
    highlightPostTag: "</mark>"
    attributesToHighlight:
    - title
    - heading
    - content
    - chapeau-text
    attributesToSnippet:
    - content:20
    - chapeau-text:20
